//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Inventario_BDEntities : DbContext
    {
        public Inventario_BDEntities()
            : base("name=Inventario_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CATEGORIA> TBL_CATEGORIA { get; set; }
        public virtual DbSet<TBL_DEPARTAMENTO> TBL_DEPARTAMENTO { get; set; }
        public virtual DbSet<TBL_EMPLEADO> TBL_EMPLEADO { get; set; }
        public virtual DbSet<TBL_MODULO> TBL_MODULO { get; set; }
        public virtual DbSet<TBL_PANTALLA> TBL_PANTALLA { get; set; }
        public virtual DbSet<TBL_PERMISO_PANTALLA> TBL_PERMISO_PANTALLA { get; set; }
        public virtual DbSet<TBL_PRODUCTO> TBL_PRODUCTO { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
    }
}
