//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public string USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<int> ID_MODULO { get; set; }
    
        public virtual TBL_EMPLEADO TBL_EMPLEADO { get; set; }
    }
}
