//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERMISO_PANTALLA
    {
        public int ID_PERMISO { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<int> ID_PANTALLA { get; set; }
        public string USUARIO { get; set; }
    
        public virtual TBL_PANTALLA TBL_PANTALLA { get; set; }
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
